// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "area": Application User Types
//
// Command:
// $ goagen
// --design=github.com/hryktrd/goaTest/design
// --out=$(GOPATH)\src\github.com\hryktrd\goaTest
// --version=v1.3.1

package client
