// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "area": Application Controllers
//
// Command:
// $ goagen
// --design=github.com/hryktrd/goaTest/design
// --out=$(GOPATH)\src\github.com\hryktrd\goaTest
// --regen=true
// --version=v1.3.1

package app

import (
	"context"
	"github.com/goadesign/goa"
	"net/http"
)

// initService sets up the service encoders, decoders and mux.
func initService(service *goa.Service) {
	// Setup encoders and decoders
	service.Encoder.Register(goa.NewJSONEncoder, "application/json")
	service.Encoder.Register(goa.NewGobEncoder, "application/gob", "application/x-gob")
	service.Encoder.Register(goa.NewXMLEncoder, "application/xml")
	service.Decoder.Register(goa.NewJSONDecoder, "application/json")
	service.Decoder.Register(goa.NewGobDecoder, "application/gob", "application/x-gob")
	service.Decoder.Register(goa.NewXMLDecoder, "application/xml")

	// Setup default encoder and decoder
	service.Encoder.Register(goa.NewJSONEncoder, "*/*")
	service.Decoder.Register(goa.NewJSONDecoder, "*/*")
}

// PointController is the controller interface for the Point actions.
type PointController interface {
	goa.Muxer
	List(*ListPointContext) error
	Show(*ShowPointContext) error
}

// MountPointController "mounts" a Point resource controller on the given service.
func MountPointController(service *goa.Service, ctrl PointController) {
	initService(service)
	var h goa.Handler

	h = func(ctx context.Context, rw http.ResponseWriter, req *http.Request) error {
		// Check if there was an error loading the request
		if err := goa.ContextError(ctx); err != nil {
			return err
		}
		// Build the context
		rctx, err := NewListPointContext(ctx, req, service)
		if err != nil {
			return err
		}
		return ctrl.List(rctx)
	}
	h = handleSecurity("BasicAuth", h)
	service.Mux.Handle("GET", "/points/", ctrl.MuxHandler("list", h, nil))
	service.LogInfo("mount", "ctrl", "Point", "action", "List", "route", "GET /points/", "security", "BasicAuth")

	h = func(ctx context.Context, rw http.ResponseWriter, req *http.Request) error {
		// Check if there was an error loading the request
		if err := goa.ContextError(ctx); err != nil {
			return err
		}
		// Build the context
		rctx, err := NewShowPointContext(ctx, req, service)
		if err != nil {
			return err
		}
		return ctrl.Show(rctx)
	}
	h = handleSecurity("BasicAuth", h)
	service.Mux.Handle("GET", "/points/:pointId", ctrl.MuxHandler("show", h, nil))
	service.LogInfo("mount", "ctrl", "Point", "action", "Show", "route", "GET /points/:pointId", "security", "BasicAuth")
}
