// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "area": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=github.com/hryktrd/goaTest/design
// --out=$(GOPATH)\src\github.com\hryktrd\goaTest
// --regen=true
// --version=v1.3.1

package app

import (
	"fmt"
	"strings"
)

// PointHref returns the resource href.
func PointHref(pointID interface{}) string {
	parampointID := strings.TrimLeftFunc(fmt.Sprintf("%v", pointID), func(r rune) bool { return r == '/' })
	return fmt.Sprintf("/points/%v", parampointID)
}
